//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Proyecto.Web.wsEstudiantes {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsEstudiantesSoap", Namespace="http://tempuri.org/")]
    public partial class wsEstudiantes : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback insertarEstudianteOperationCompleted;
        
        private System.Threading.SendOrPostCallback actualizarEstudianteOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetListOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsEstudiantes() {
            this.Url = global::Proyecto.Web.Properties.Settings.Default.Proyecto_Web_wsEstudiantes_wsEstudiantes;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event insertarEstudianteCompletedEventHandler insertarEstudianteCompleted;
        
        /// <remarks/>
        public event actualizarEstudianteCompletedEventHandler actualizarEstudianteCompleted;
        
        /// <remarks/>
        public event GetListCompletedEventHandler GetListCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insertarEstudiante", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string insertarEstudiante(TbEstudiante estudiante) {
            object[] results = this.Invoke("insertarEstudiante", new object[] {
                        estudiante});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void insertarEstudianteAsync(TbEstudiante estudiante) {
            this.insertarEstudianteAsync(estudiante, null);
        }
        
        /// <remarks/>
        public void insertarEstudianteAsync(TbEstudiante estudiante, object userState) {
            if ((this.insertarEstudianteOperationCompleted == null)) {
                this.insertarEstudianteOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertarEstudianteOperationCompleted);
            }
            this.InvokeAsync("insertarEstudiante", new object[] {
                        estudiante}, this.insertarEstudianteOperationCompleted, userState);
        }
        
        private void OninsertarEstudianteOperationCompleted(object arg) {
            if ((this.insertarEstudianteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertarEstudianteCompleted(this, new insertarEstudianteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/actualizarEstudiante", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string actualizarEstudiante(TbEstudiante estudiante) {
            object[] results = this.Invoke("actualizarEstudiante", new object[] {
                        estudiante});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void actualizarEstudianteAsync(TbEstudiante estudiante) {
            this.actualizarEstudianteAsync(estudiante, null);
        }
        
        /// <remarks/>
        public void actualizarEstudianteAsync(TbEstudiante estudiante, object userState) {
            if ((this.actualizarEstudianteOperationCompleted == null)) {
                this.actualizarEstudianteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnactualizarEstudianteOperationCompleted);
            }
            this.InvokeAsync("actualizarEstudiante", new object[] {
                        estudiante}, this.actualizarEstudianteOperationCompleted, userState);
        }
        
        private void OnactualizarEstudianteOperationCompleted(object arg) {
            if ((this.actualizarEstudianteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.actualizarEstudianteCompleted(this, new actualizarEstudianteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TbEstudiante[] GetList() {
            object[] results = this.Invoke("GetList", new object[0]);
            return ((TbEstudiante[])(results[0]));
        }
        
        /// <remarks/>
        public void GetListAsync() {
            this.GetListAsync(null);
        }
        
        /// <remarks/>
        public void GetListAsync(object userState) {
            if ((this.GetListOperationCompleted == null)) {
                this.GetListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetListOperationCompleted);
            }
            this.InvokeAsync("GetList", new object[0], this.GetListOperationCompleted, userState);
        }
        
        private void OnGetListOperationCompleted(object arg) {
            if ((this.GetListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetListCompleted(this, new GetListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TbEstudiante {
        
        private long idField;
        
        private string estPrimerNombreField;
        
        private string estSegundoNombreField;
        
        private string estPrimerApellidoField;
        
        private string estSegundoApellidoField;
        
        private string estDireccionField;
        
        private string estTelefonoField;
        
        private string estGrupoField;
        
        private string estEdadField;
        
        private string estAcudientePrimerNombreField;
        
        private string estAcudienteSegundoNombreField;
        
        private string estAcudientePrimerApellidoField;
        
        private string estAcudienteSegundoApellidoField;
        
        private string estAcudienteParentescoField;
        
        private string estAcudienteDireccionField;
        
        private string estAcudienteCorreoField;
        
        private tbEstudiante_Tarjeta[] tbEstudiante_TarjetaField;
        
        /// <remarks/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string EstPrimerNombre {
            get {
                return this.estPrimerNombreField;
            }
            set {
                this.estPrimerNombreField = value;
            }
        }
        
        /// <remarks/>
        public string EstSegundoNombre {
            get {
                return this.estSegundoNombreField;
            }
            set {
                this.estSegundoNombreField = value;
            }
        }
        
        /// <remarks/>
        public string EstPrimerApellido {
            get {
                return this.estPrimerApellidoField;
            }
            set {
                this.estPrimerApellidoField = value;
            }
        }
        
        /// <remarks/>
        public string EstSegundoApellido {
            get {
                return this.estSegundoApellidoField;
            }
            set {
                this.estSegundoApellidoField = value;
            }
        }
        
        /// <remarks/>
        public string EstDireccion {
            get {
                return this.estDireccionField;
            }
            set {
                this.estDireccionField = value;
            }
        }
        
        /// <remarks/>
        public string EstTelefono {
            get {
                return this.estTelefonoField;
            }
            set {
                this.estTelefonoField = value;
            }
        }
        
        /// <remarks/>
        public string EstGrupo {
            get {
                return this.estGrupoField;
            }
            set {
                this.estGrupoField = value;
            }
        }
        
        /// <remarks/>
        public string EstEdad {
            get {
                return this.estEdadField;
            }
            set {
                this.estEdadField = value;
            }
        }
        
        /// <remarks/>
        public string EstAcudientePrimerNombre {
            get {
                return this.estAcudientePrimerNombreField;
            }
            set {
                this.estAcudientePrimerNombreField = value;
            }
        }
        
        /// <remarks/>
        public string EstAcudienteSegundoNombre {
            get {
                return this.estAcudienteSegundoNombreField;
            }
            set {
                this.estAcudienteSegundoNombreField = value;
            }
        }
        
        /// <remarks/>
        public string EstAcudientePrimerApellido {
            get {
                return this.estAcudientePrimerApellidoField;
            }
            set {
                this.estAcudientePrimerApellidoField = value;
            }
        }
        
        /// <remarks/>
        public string EstAcudienteSegundoApellido {
            get {
                return this.estAcudienteSegundoApellidoField;
            }
            set {
                this.estAcudienteSegundoApellidoField = value;
            }
        }
        
        /// <remarks/>
        public string EstAcudienteParentesco {
            get {
                return this.estAcudienteParentescoField;
            }
            set {
                this.estAcudienteParentescoField = value;
            }
        }
        
        /// <remarks/>
        public string EstAcudienteDireccion {
            get {
                return this.estAcudienteDireccionField;
            }
            set {
                this.estAcudienteDireccionField = value;
            }
        }
        
        /// <remarks/>
        public string EstAcudienteCorreo {
            get {
                return this.estAcudienteCorreoField;
            }
            set {
                this.estAcudienteCorreoField = value;
            }
        }
        
        /// <remarks/>
        public tbEstudiante_Tarjeta[] tbEstudiante_Tarjeta {
            get {
                return this.tbEstudiante_TarjetaField;
            }
            set {
                this.tbEstudiante_TarjetaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class tbEstudiante_Tarjeta {
        
        private long idField;
        
        private System.Nullable<long> idEstudiantesField;
        
        private System.Nullable<long> idTarjetasField;
        
        private tbAsistencia[] tbAsistenciaField;
        
        private TbEstudiante tbEstudianteField;
        
        private tbTarjetas tbTarjetasField;
        
        /// <remarks/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> IdEstudiantes {
            get {
                return this.idEstudiantesField;
            }
            set {
                this.idEstudiantesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> IdTarjetas {
            get {
                return this.idTarjetasField;
            }
            set {
                this.idTarjetasField = value;
            }
        }
        
        /// <remarks/>
        public tbAsistencia[] tbAsistencia {
            get {
                return this.tbAsistenciaField;
            }
            set {
                this.tbAsistenciaField = value;
            }
        }
        
        /// <remarks/>
        public TbEstudiante TbEstudiante {
            get {
                return this.tbEstudianteField;
            }
            set {
                this.tbEstudianteField = value;
            }
        }
        
        /// <remarks/>
        public tbTarjetas tbTarjetas {
            get {
                return this.tbTarjetasField;
            }
            set {
                this.tbTarjetasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class tbAsistencia {
        
        private long idField;
        
        private System.Nullable<long> estudiante_Tarjeta_IdField;
        
        private System.Nullable<System.DateTime> fechayHoraField;
        
        private tbEstudiante_Tarjeta tbEstudiante_TarjetaField;
        
        /// <remarks/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> Estudiante_Tarjeta_Id {
            get {
                return this.estudiante_Tarjeta_IdField;
            }
            set {
                this.estudiante_Tarjeta_IdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> FechayHora {
            get {
                return this.fechayHoraField;
            }
            set {
                this.fechayHoraField = value;
            }
        }
        
        /// <remarks/>
        public tbEstudiante_Tarjeta tbEstudiante_Tarjeta {
            get {
                return this.tbEstudiante_TarjetaField;
            }
            set {
                this.tbEstudiante_TarjetaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class tbTarjetas {
        
        private long idField;
        
        private string numeroRfidField;
        
        private tbEstudiante_Tarjeta[] tbEstudiante_TarjetaField;
        
        /// <remarks/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroRfid {
            get {
                return this.numeroRfidField;
            }
            set {
                this.numeroRfidField = value;
            }
        }
        
        /// <remarks/>
        public tbEstudiante_Tarjeta[] tbEstudiante_Tarjeta {
            get {
                return this.tbEstudiante_TarjetaField;
            }
            set {
                this.tbEstudiante_TarjetaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void insertarEstudianteCompletedEventHandler(object sender, insertarEstudianteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insertarEstudianteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insertarEstudianteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void actualizarEstudianteCompletedEventHandler(object sender, actualizarEstudianteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class actualizarEstudianteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal actualizarEstudianteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetListCompletedEventHandler(object sender, GetListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TbEstudiante[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TbEstudiante[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591