//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Logica.Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Cnx : DbContext
    {
        public Cnx()
            : base("name=Cnx")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbAsistencia> tbAsistencia { get; set; }
        public virtual DbSet<tbDocentes> tbDocentes { get; set; }
        public virtual DbSet<TbEstudiante> TbEstudiante { get; set; }
        public virtual DbSet<tbEstudiante_Tarjeta> tbEstudiante_Tarjeta { get; set; }
        public virtual DbSet<tbGrados> tbGrados { get; set; }
        public virtual DbSet<tbTarjetas> tbTarjetas { get; set; }
        public virtual DbSet<tbUsuarios> tbUsuarios { get; set; }
    }
}
