//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAsistencia
    {
        public long Id { get; set; }
        public Nullable<long> Estudiante_Tarjeta_Id { get; set; }
        public Nullable<System.DateTime> FechayHora { get; set; }
    
        public virtual tbEstudiante_Tarjeta tbEstudiante_Tarjeta { get; set; }
    }
}
