//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDocentes
    {
        public long doceId { get; set; }
        public string docePrimerNombre { get; set; }
        public string doceSegundoNombre { get; set; }
        public string docePrimerApellido { get; set; }
        public string doceSegundoApellido { get; set; }
        public string doceCedula { get; set; }
        public string doceDireccion { get; set; }
        public string doceTelefono { get; set; }
        public string doceCelular { get; set; }
        public string doceCorreo { get; set; }
        public string doceNivelAcademico { get; set; }
        public string doceArea { get; set; }
        public Nullable<long> doceIdAsignatura { get; set; }
    }
}
