//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEstudiante_Tarjeta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbEstudiante_Tarjeta()
        {
            this.tbAsistencia = new List<tbAsistencia>();
        }
    
        public long Id { get; set; }
        public Nullable<long> IdEstudiantes { get; set; }
        public Nullable<long> IdTarjetas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<tbAsistencia> tbAsistencia { get; set; }
        public virtual TbEstudiante TbEstudiante { get; set; }
        public virtual tbTarjetas tbTarjetas { get; set; }
    }
}
