//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbEstudiante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TbEstudiante()
        {
            this.tbEstudiante_Tarjeta = new List<tbEstudiante_Tarjeta>();
        }
    
        public long Id { get; set; }
        public string EstPrimerNombre { get; set; }
        public string EstSegundoNombre { get; set; }
        public string EstPrimerApellido { get; set; }
        public string EstSegundoApellido { get; set; }
        public string EstDireccion { get; set; }
        public string EstTelefono { get; set; }
        public string EstGrupo { get; set; }
        public string EstEdad { get; set; }
        public string EstAcudientePrimerNombre { get; set; }
        public string EstAcudienteSegundoNombre { get; set; }
        public string EstAcudientePrimerApellido { get; set; }
        public string EstAcudienteSegundoApellido { get; set; }
        public string EstAcudienteParentesco { get; set; }
        public string EstAcudienteDireccion { get; set; }
        public string EstAcudienteCorreo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<tbEstudiante_Tarjeta> tbEstudiante_Tarjeta { get; set; }
    }
}
