//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbGrados
    {
        public string graCodigo { get; set; }
        public string graGrado { get; set; }
        public string graDetalle { get; set; }
        public Nullable<decimal> graNum_estudiante { get; set; }
        public string graJornada { get; set; }
        public string graNivel { get; set; }
        public string graPlantilla { get; set; }
    }
}
